# Generated by Django 3.1.7 on 2021-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='memmo',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
