# Generated by Django 3.1.7 on 2021-04-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_memmo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headliner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adr', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='memmo',
            field=models.TextField(blank=True),
        ),
    ]
