# Generated by Django 3.1.7 on 2021-04-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210407_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='Contacts',
        ),
    ]
